{
 "title": "MAS",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(db_connections_usage,instance)"
    }
   },
   {
    "name": "bucket",
    "label": "bucket",
    "query": "30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "server_address",
    "label": "Server Address",
    "query": {
     "query": "label_values(http_client_request_duration_milliseconds_bucket,server_address)"
    }
   },
   {
    "name": "http_route",
    "label": "http_route",
    "query": {
     "query": "label_values(http_server_active_requests,http_route)"
    }
   },
   {
    "name": "job_queue_name",
    "label": "Job Queue Name",
    "query": {
     "query": "label_values(job_process_duration_milliseconds_bucket,job_queue_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Info",
   "type": "stat",
   "gridPos": { "h": 14, "w": 11, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "target_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HTTP Server Active Requests",
   "type": "gauge",
   "description": "The number of in-flight requests",
   "gridPos": { "h": 14, "w": 13, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "http_server_active_requests", "legendFormat": "{{http_route}}" }
   ]
  },
  {
   "title": "Max DB Connections",
   "type": "gauge",
   "description": "The maximum number of open connections allowed",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "db_connections_max", "legendFormat": "__auto" },
    { "expr": "sum(db_connections_usage)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "DB Connections Usage",
   "type": "timeseries",
   "description": "The number of connections that are currently in `state` described by the state attribute.",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 14 },
   "targets": [
    {
     "expr": "db_connections_usage{instance=\"$instance\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "DB Connection Create Time",
   "type": "timeseries",
   "description": "The time it took to create a new connection.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(db_client_connections_create_time_milliseconds_bucket[$bucket])) by (le))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(db_client_connections_create_time_milliseconds_bucket[$bucket])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(db_client_connections_create_time_milliseconds_bucket[$bucket])) by (le))",
     "legendFormat": "75%"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(db_client_connections_create_time_milliseconds_bucket[$bucket])) by (le))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.25, sum(rate(db_client_connections_create_time_milliseconds_bucket[$bucket])) by (le))",
     "legendFormat": "25%"
    },
    {
     "expr": "sum(rate(db_client_connections_create_time_milliseconds_sum[$bucket])) / sum(rate(db_client_connections_create_time_milliseconds_count[$bucket]))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "HTTP Client Request Duration",
   "type": "timeseries",
   "description": "Duration of HTTP client requests",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_client_request_duration_milliseconds_bucket{server_address=~\"$server_address\"}[$bucket])) by (le))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_client_request_duration_milliseconds_bucket{server_address=~\"$server_address\"}[$bucket])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(http_client_request_duration_milliseconds_bucket{server_address=~\"$server_address\"}[$bucket])) by (le))",
     "legendFormat": "75%"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_client_request_duration_milliseconds_bucket{server_address=~\"$server_address\"}[$bucket])) by (le))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.25, sum(rate(http_client_request_duration_milliseconds_bucket{server_address=~\"$server_address\"}[$bucket])) by (le))",
     "legendFormat": "25%"
    },
    {
     "expr": "sum(rate(http_client_request_duration_milliseconds_sum{server_address=~\"$server_address\"}[$bucket])) / sum(rate(http_client_request_duration_milliseconds_count{server_address=~\"$server_address\"}[$bucket]))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Activity tracker total messages",
   "type": "timeseries",
   "description": "The number of messages received by the activity tracker",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "rate(mas_activity_tracker_messages_total[$bucket])",
     "legendFormat": "{{type}} {{session_kind}}"
    }
   ]
  },
  {
   "title": "Process Duration",
   "type": "timeseries",
   "description": "The time it takes to process a job in milliseconds",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(job_process_duration_milliseconds_bucket{job_queue_name=~\"$job_queue_name\"}[$bucket])) by (le))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(job_process_duration_milliseconds_bucket{job_queue_name=~\"$job_queue_name\"}[$bucket])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(job_process_duration_milliseconds_bucket{job_queue_name=~\"$job_queue_name\"}[$bucket])) by (le))",
     "legendFormat": "75%"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(job_process_duration_milliseconds_bucket{job_queue_name=~\"$job_queue_name\"}[$bucket])) by (le))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.25, sum(rate(job_process_duration_milliseconds_bucket{job_queue_name=~\"$job_queue_name\"}[$bucket])) by (le))",
     "legendFormat": "25%"
    },
    {
     "expr": "sum(rate(job_process_duration_milliseconds_sum{job_queue_name=~\"$job_queue_name\"}[$bucket])) / sum(rate(job_process_duration_milliseconds_count{job_queue_name=~\"$job_queue_name\"}[$bucket]))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "HTTP Server request duration",
   "type": "timeseries",
   "description": "The number of in-flight requests",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_bucket{http_route=~\"$http_route\"}[$bucket])) by (le))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_server_duration_bucket{http_route=~\"$http_route\"}[$bucket])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(http_server_duration_bucket{http_route=~\"$http_route\"}[$bucket])) by (le))",
     "legendFormat": "75%"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_bucket{http_route=~\"$http_route\"}[$bucket])) by (le))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.25, sum(rate(http_server_duration_bucket{http_route=~\"$http_route\"}[$bucket])) by (le))",
     "legendFormat": "25%"
    },
    {
     "expr": "sum(rate(http_server_duration_sum{http_route=~\"$http_route\"}[$bucket])) / sum(rate(http_server_duration_count{http_route=~\"$http_route\"}[$bucket]))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Activity Tracker Flush Time",
   "type": "timeseries",
   "description": "The time it took to flush the activity tracker",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(mas_activity_tracker_flush_time_milliseconds_bucket[$bucket])) by (le))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(mas_activity_tracker_flush_time_milliseconds_bucket[$bucket])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(mas_activity_tracker_flush_time_milliseconds_bucket[$bucket])) by (le))",
     "legendFormat": "75%"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(mas_activity_tracker_flush_time_milliseconds_bucket[$bucket])) by (le))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.25, sum(rate(mas_activity_tracker_flush_time_milliseconds_bucket[$bucket])) by (le))",
     "legendFormat": "25%"
    },
    {
     "expr": "sum(rate(mas_activity_tracker_flush_time_milliseconds_sum[$bucket])) / sum(rate(mas_activity_tracker_flush_time_milliseconds_sum[$bucket]))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Worker Tick Duration",
   "type": "timeseries",
   "description": "How much time the worker took to tick, including performing leader duties",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(job_worker_tick_duration_bucket[$bucket])) by (le))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(job_worker_tick_duration_bucket[$bucket])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(job_worker_tick_duration_bucket[$bucket])) by (le))",
     "legendFormat": "75%"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(job_worker_tick_duration_bucket[$bucket])) by (le))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.25, sum(rate(job_worker_tick_duration_bucket[$bucket])) by (le))",
     "legendFormat": "25%"
    },
    {
     "expr": "sum(rate(job_worker_tick_duration_sum[$bucket])) / sum(rate(job_worker_tick_duration_count[$bucket]))",
     "legendFormat": "Average"
    }
   ]
  }
 ]
}